# -*- coding: utf-8 -*-
"""Maraude.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FaJbmfEdUYCexMOVltMrQdpC-5zqV8ul
"""

import traceback
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload
import io
from PyPDF2 import PdfReader, PdfWriter
import json
import gspread
from gspread_dataframe import get_as_dataframe
import pandas as pd
from PyPDF2 import PdfReader, PdfWriter
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
from PyPDF2 import PdfReader, PdfWriter
from matplotlib.figure import Figure
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from reportlab.pdfgen import canvas as rl_canvas
from reportlab.lib.utils import ImageReader
import math
import os
import matplotlib.pyplot as plt
from IPython.display import Image, display
import fitz  # PyMuPDF
from PIL import Image as PILImage
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import matplotlib.ticker as mtick
from matplotlib.patches import Patch
import io
import re
import shutil
import zipfile
from google.colab import drive, files

from google.colab import auth
from google.auth import default
import unicodedata
import re
import torch
from sentence_transformers import SentenceTransformer, util
import sys
sys.path.append(os.path.abspath("/Code-PAT"))
from utils import *


# Import

def import_maraude(client):
    query = """
    SELECT *
    FROM `crf-pat.dataset_PAT_2025.crf_pat_2025_maraude`
    """
    df_maraude = client.query(query).to_dataframe()

    query = """
    SELECT *
    FROM `crf-pat.dataset_PAT_2025.rattachement_court`
    """
    df_rattachement_court = client.query(query).to_dataframe()

    return df_maraude, df_rattachement_court

# Clean

def enrich_maraude_rattachement(df_ref_structure, df_maraude, col="maraude_structure_id_fk"):
    """
    Applique le rattachement successif sur df_maraude.
    Retourne un df_maraude enrichi.
    """
    return apply_rattachement_successif(df_ref_structure, df_maraude, col=col)

def filter_maraude_on_ref_structure(
    df_maraude: pd.DataFrame,
    df_ref_structure: pd.DataFrame,
    col_maraude: str = "maraude_structure_id_fk",
    col_ref: str = "n_structure",
    verbose: bool = True
) -> pd.DataFrame:
    """
    Conserve uniquement les lignes de df_maraude dont df_maraude[col_maraude] est présent
    dans df_ref_structure[col_ref]. Retourne un nouveau df (ne modifie pas l'original).
    """

    if col_maraude not in df_maraude.columns:
        raise ValueError(f"df_maraude doit contenir la colonne '{col_maraude}'.")
    if col_ref not in df_ref_structure.columns:
        raise ValueError(f"df_ref_structure doit contenir la colonne '{col_ref}'.")

    d = df_maraude.copy()

    # Normalisation des ids en Int64 nullable pour éviter les mismatches type str/int
    d[col_maraude] = pd.to_numeric(d[col_maraude], errors="coerce").astype("Int64")
    ref_ids = pd.to_numeric(df_ref_structure[col_ref], errors="coerce").astype("Int64")

    ref_set = set(ref_ids.dropna().tolist())

    n0 = len(d)
    d = d[d[col_maraude].isin(ref_set)].copy()
    n1 = len(d)

    if verbose:
        print(f"📌 Filtre structures ref: {n1:,}/{n0:,} lignes conservées (supprimées: {n0-n1:,}).")

    return d

def prep_nb_maraudes_sigma(df, filtre_annee_fn=None):
    cols_keep = [
        "maraude_id_fk",
        "maraude_structure_id_fk",
        "maraude_statut",
        "maraude_date_debut",
        "maraude_date_fin",
    ]

    missing = [c for c in cols_keep if c not in df.columns]
    if missing:
        print("Colonnes manquantes:", missing)

    d = df.loc[:, [c for c in cols_keep if c in df.columns]].copy()

    d = d.drop_duplicates()

    d = d.loc[d["maraude_statut"] == "FINISHED"].copy()

    if filtre_annee_fn is not None:
        filtre_annee_fn(d, "maraude_date_debut")  # si ta fonction modifie d "in place"
        # ou: d = filtre_annee_fn(d, "maraude_date_debut") si elle retourne un df

    return d


def prep_nb_personnes_rencontrees_sigma(df, filtre_annee_fn=None):
    cols_keep = ["maraude_id_fk","maraude_structure_id_fk","maraude_statut","maraude_date_debut","maraude_date_fin", 'maraude_rencontre_beneficiaire_id_fk',
       'maraude_rencontre_contact_realise', 'maraude_rencontre_typologie',
       'maraude_rencontre_nb_hommes', 'maraude_rencontre_nb_femmes',
       'maraude_rencontre_nb_transgenres', 'maraude_rencontre_nb_mineurs',
       'maraude_rencontre_nb_inconnus']

    missing = [c for c in cols_keep if c not in df.columns]
    if missing:
        print("Colonnes manquantes:", missing)

    d = df.loc[:, [c for c in cols_keep if c in df.columns]].copy()

    d = d.drop_duplicates()

    d = d.loc[d["maraude_statut"] == "FINISHED"].copy()

    d = d.loc[d["maraude_rencontre_contact_realise"] == "Oui"].copy()

    if filtre_annee_fn is not None:
        filtre_annee_fn(d, "maraude_date_debut")  # si ta fonction modifie d "in place"
        # ou: d = filtre_annee_fn(d, "maraude_date_debut") si elle retourne un df

    return d

def clean_maraudes(df_maraude):
    df_nb_personnes_rencontrees_sigma = prep_nb_personnes_rencontrees_sigma(df_maraude)
    df_Nb_maraudes_SIGMA = prep_nb_maraudes_sigma(df_maraude)

    return df_nb_personnes_rencontrees_sigma, df_Nb_maraudes_SIGMA


#Calcul Structure

def calc_nb_maraudes_sigma(df_prep,
                           col_structure="maraude_structure_id_fk",
                           col_id="maraude_id_fk",
                           out_structure="n_structure",
                           out_count="Maraude Nb_maraudes_SIGMA"):
    df_out = df_prep.groupby(col_structure, as_index=False)[col_id].count()
    df_out.columns = [out_structure, out_count]
    return df_out



def add_nb_personnes(df,
                     out_col="nb personnes",
                     cols=None,
                     col_typologie="maraude_rencontre_typologie"):
    if cols is None:
        cols = [
            "maraude_rencontre_nb_hommes",
            "maraude_rencontre_nb_femmes",
            "maraude_rencontre_nb_transgenres",
            "maraude_rencontre_nb_mineurs",
            "maraude_rencontre_nb_inconnus",
        ]

    d = df.copy()
    missing = [c for c in cols + [col_typologie] if c not in d.columns]
    if missing:
        raise ValueError(f"Colonnes manquantes pour calculer '{out_col}': {missing}")

    d[cols] = d[cols].apply(pd.to_numeric, errors="coerce").fillna(0)
    d[out_col] = d[cols].sum(axis=1)

    # +1 si typologie == "individu"
    d[out_col] += (d[col_typologie].astype(str).str.strip().str.lower() == "individu").astype(int)

    return d

#Calcul DT

def Nb_maraudes_SIGMA_DT(df, filtre=None,
                              col_structure="DT_de_rattachement",
                              col_user="Maraude Nb_maraudes_SIGMA",
                              out_col="Maraude Nb_maraudes_SIGMA"):
    d = df.query(filtre) if filtre else df
    return (d.groupby(col_structure)[col_user]
              .sum()
              .rename(out_col)
              .to_frame() #transforme la serie en dataframe
              .reset_index())

    #Calcul DT

def nb_contact_SIGMA_DT(df, filtre=None,
                              col_structure="DT_de_rattachement",
                              col_user="Maraude Nb_contacts",
                              out_col="Maraude Nb_contacts"):
    d = df.query(filtre) if filtre else df
    return (d.groupby(col_structure)[col_user]
              .sum()
              .rename(out_col)
              .to_frame() #transforme la serie en dataframe
              .reset_index())


def nb_personnes_rencontrees_SIGMA_DT(df, filtre=None,
                              col_structure="DT_de_rattachement",
                              col_user="Maraude Nb_personnes_rencontrees",
                              out_col="Maraude Nb_personnes_rencontrees"):
    d = df.query(filtre) if filtre else df
    return (d.groupby(col_structure)[col_user]
              .sum()
              .rename(out_col)
              .to_frame() #transforme la serie en dataframe
              .reset_index())

def indicateurs_maraude(df_nb_personnes_rencontrees_sigma, df_Nb_maraudes_SIGMA,df_rattachement_court):

  #calcul Nombre de maraude par structure
  df_Nb_maraudes_SIGMA = df_Nb_maraudes_SIGMA.rename(columns = {'maraude_structure_id_fk' : 'n_structure'})

  df_Nb_maraudes_SIGMA = df_Nb_maraudes_SIGMA.groupby("n_structure", as_index=False)["maraude_id_fk"].count()
  df_Nb_maraudes_SIGMA.columns = ["n_structure", "Maraude Nb_maraudes_SIGMA"]

  #calcul Nombre de maraude par DT

  df_Nb_maraudes_SIGMA.columns = ["n_structure", "Maraude Nb_maraudes_SIGMA"]
  df_Nb_maraudes_SIGMA = pd.merge(df_Nb_maraudes_SIGMA, df_rattachement_court, on='n_structure', how="left")
  
  df_Nb_maraudes_SIGMA_DT = Nb_maraudes_SIGMA_DT(df_Nb_maraudes_SIGMA)
  #Calcul du nombre de contacts par structure
  df_nb_personnes_rencontrees_sigma = df_nb_personnes_rencontrees_sigma.rename(columns = {'maraude_structure_id_fk' : 'n_structure'})
  df_nb_personnes_rencontrees_sigma = add_nb_personnes(df_nb_personnes_rencontrees_sigma)

  df_nb_personnes_rencontrees_SIGMA = (
      df_nb_personnes_rencontrees_sigma
      .groupby("n_structure", as_index=False)["nb personnes"]
      .sum()
  )
  df_nb_personnes_rencontrees_SIGMA.columns = ["n_structure", "Maraude Nb_contacts"]
  #Calcul du nombre de contacts par DT


  df_nb_contacts_SIGMA_struct = pd.merge(df_nb_personnes_rencontrees_SIGMA , df_rattachement_court, on='n_structure', how="left") #a conserver dans le code principal

  df_nb_contacts_SIGMA_DT = nb_contact_SIGMA_DT(df_nb_personnes_rencontrees_SIGMA)

  #Calcul du nombre de personnes différentes rencontrées

  df_max_nb_personnes = df_nb_personnes_rencontrees_sigma.loc[
      df_nb_personnes_rencontrees_sigma.groupby("maraude_rencontre_beneficiaire_id_fk")["nb personnes"].idxmax(),
      ["maraude_rencontre_beneficiaire_id_fk", "n_structure", "nb personnes"]
  ].reset_index(drop=True)

  df_max_nb_personnes.columns = ["maraude_rencontre_beneficiaire_id_fk","n_structure", "Maraude Nb_personnes_rencontrees"]

  df_max_nb_personnes_struct = df_max_nb_personnes.groupby("n_structure")["Maraude Nb_personnes_rencontrees"].sum() #a conserver dans le code principal

  df_nb_personnes_rencontrees_SIGMA_Struct = pd.merge(df_max_nb_personnes_struct , df_rattachement_court, on='n_structure', how="left") #a conserver dans le code principal
  
  #Calcul du nombre de personnes différentes rencontrées par DT
  df_nb_personnes_rencontrees_SIGMA_DT = nb_personnes_rencontrees_SIGMA_DT(df_nb_personnes_rencontrees_SIGMA_Struct)

  return df_Nb_maraudes_SIGMA, df_Nb_maraudes_SIGMA_DT, df_nb_contacts_SIGMA_struct, df_nb_contacts_SIGMA_DT, df_nb_personnes_rencontrees_SIGMA_Struct,   df_nb_personnes_rencontrees_SIGMA_DT

def lignes_vides(df, col_code_structure, label=None, raise_error=False):

    #Vérifie si une colonne contient des NaN ou des valeurs vides ("").
    #Affiche un message OK/KO. Optionnellement lève une erreur.

    s = df[col_code_structure]
    lignes_vides = df[s.isna() | (s.astype(str).str.strip() == "")]

    col_name = label or col_code_structure
    if not lignes_vides.empty:
        msg = f"❌ {len(lignes_vides)} valeur(s) manquante(s) ou vide(s) détectée(s) dans '{col_name}'."
        print(msg)
        if raise_error:
            raise ValueError(msg)
        return False, lignes_vides
    else:
        print(f"✅ Aucun NaN ou valeur vide détecté dans '{col_name}'.")
        return True, lignes_vides

def verification_maraude(df_ref_structure,df_Nb_maraudes_SIGMA,df_Nb_maraudes_SIGMA_DT, df_nb_personnes_rencontrees_sigma, df_nb_personnes_rencontrees_SIGMA,df_nb_personnes_rencontrees_SIGMA_DT,df_maraude):
  # 1. Vérification des NaN ou valeurs vides
  Sigma_vide = lignes_vides(df_Nb_maraudes_SIGMA, "DT_de_rattachement")
  verifier_colonne_structure(df_Nb_maraudes_SIGMA, "n_structure", df_ref_structure)
  # Vérifications

  Maraude_etab = sum(Sigma_vide[1]['Maraude Nb_maraudes_SIGMA'])

  # #1. vérification du nombre de maraude dans Sigma
  # if df_Nb_maraudes_SIGMA_DT["Maraude Nb_maraudes_SIGMA"].sum() + Maraude_etab != len(df_PREP_Nb_maraudes_SIGMA):
  #     raise ValueError(
  #         f"Incohérence: somme des maraudes par DT={Nb_maraudes_SIGMA_DT['Maraude Nb_maraudes_SIGMA'].sum()} vs total des maraudes finies={len(df_PREP_Nb_maraudes_SIGMA)}"
  #     )
  # else:
  #     print("OK ✅ : la somme du nb de maraude dans SIGMA correspond au nombre de lignes de df_PREP_Nb_maraudes_SIGMA")

      # Vérifications

  #1. vérification du personnes_rencontrees dans Sigma
  if df_nb_personnes_rencontrees_SIGMA["Maraude Nb_contacts"].sum() != df_nb_personnes_rencontrees_sigma["nb personnes"].sum():
      raise ValueError(
          f"Incohérence: Maraude Nb_contacts ={df_nb_personnes_rencontrees_SIGMA["Maraude Nb_contacts"].sum()} vs nb_lignes df_Nb_maraudes_sigma={df_nb_personnes_rencontrees_sigma["nb personnes"].sum()}"
      )
  else:
      print("OK ✅ : la somme du nb de maraude dans SIGMA correspond au nombre de lignes de df_Nb_maraudes_SIGMA")

  # Vérifications

  Personnes_rencontrees = lignes_vides(df_nb_personnes_rencontrees_SIGMA, "DT_de_rattachement")[1]['Maraude Nb_contacts'].sum()

  #1. vérification du nombre de personnes rencontrées par maraude dans Sigma
  if df_nb_personnes_rencontrees_SIGMA_DT["Maraude Nb_contacts"].sum() + Personnes_rencontrees!= df_nb_personnes_rencontrees_SIGMA["Maraude Nb_contacts"].sum():
      raise ValueError(
          f"Incohérence: somme des maraudes par DT={nb_personnes_rencontrees_SIGMA_DT["Maraude Nb_contacts"].sum()} vs total des maraudes finies={df_nb_personnes_rencontrees_SIGMA["Maraude Nb_contacts"].sum()}"
      )
  else:
      print("OK ✅ : la somme du nb de maraude dans SIGMA correspond au nombre de lignes de df_PREP_Nb_maraudes_SIGMA")
  # Vérifications

  #1. vérification du nombre de maraude dans Sigma
  if df_Nb_maraudes_SIGMA["Maraude Nb_maraudes_SIGMA"].sum() != len(df_maraude):
      raise ValueError(
          f"Incohérence: somme df_counts={df_Nb_maraudes_SIGMA['Maraude Nb_maraudes_SIGMA'].sum()} vs nb_lignes df_Nb_maraudes_SIGMA={len(df_maraude)}"
      )
  else:
      print("OK ✅ : la somme du nb de maraude dans SIGMA correspond au nombre de lignes de df_Nb_maraudes_SIGMA")

      # Vérifications

  #1. vérification du nombre de maraude dans Sigma
  # if df_Nb_maraudes_SIGMA["Maraude Nb_maraudes_SIGMA"].sum() != len(df_PREP_Nb_maraudes_SIGMA):
  #     raise ValueError(
  #         f"Incohérence: somme df_counts={df_counts['Maraude Nb_maraudes_SIGMA'].sum()} vs nb_lignes df_Nb_maraudes_SIGMA={len(df_Nb_maraudes_SIGMA)}"
  #     )
  # else:
  #     print("OK ✅ : la somme du nb de maraude dans SIGMA correspond au nombre de lignes de df_Nb_maraudes_SIGMA")






