# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pLhgLpzaVcVlRZnQbxIAR2SqpwYZTai9
"""

# -*- coding: utf-8 -*-
"""
maraude.py

Fonctions de préparation / calcul indicateurs Maraude (SIGMA) - PAT 2025
"""

import pandas as pd


# ---------------------------------------------------------------------
# Import
# ---------------------------------------------------------------------
def import_maraude(client):
    """
    Charge les données Maraude + rattachement_court depuis BigQuery.
    """
    query = """
    SELECT *
    FROM `crf-pat.dataset_PAT_2025.crf_pat_2025_maraude`
    """
    df_maraude = client.query(query).to_dataframe()

    query = """
    SELECT *
    FROM `crf-pat.dataset_PAT_2025.rattachement_court`
    """
    df_rattachement_court = client.query(query).to_dataframe()

    return df_maraude, df_rattachement_court


# ---------------------------------------------------------------------
# Enrich / Filter
# ---------------------------------------------------------------------
def enrich_maraude_rattachement(df_ref_structure, df_maraude, col="maraude_structure_id_fk"):
    """
    Applique le rattachement successif sur df_maraude.
    ⚠️ Si ta fonction apply_rattachement_successif retourne 4 objets, on garde uniquement df_maraude.
    """
    out = apply_rattachement_successif(df_ref_structure, df_maraude, col=col)

    # Cas 1: la fonction retourne directement un df
    if isinstance(out, pd.DataFrame):
        return out

    # Cas 2: elle retourne (df_ref_structure, c, rattachement_successif, df_maraude)
    if isinstance(out, (tuple, list)) and len(out) >= 4:
        return out[3]

    raise TypeError("apply_rattachement_successif() doit retourner un DataFrame ou un tuple dont le 4e élément est df_maraude.")


def filter_maraude_on_ref_structure(
    df_maraude: pd.DataFrame,
    df_ref_structure: pd.DataFrame,
    col_maraude: str = "maraude_structure_id_fk",
    col_ref: str = "n_structure",
    verbose: bool = True
) -> pd.DataFrame:
    """
    Conserve uniquement les lignes de df_maraude dont df_maraude[col_maraude] est présent
    dans df_ref_structure[col_ref].
    """
    if col_maraude not in df_maraude.columns:
        raise ValueError(f"df_maraude doit contenir la colonne '{col_maraude}'.")
    if col_ref not in df_ref_structure.columns:
        raise ValueError(f"df_ref_structure doit contenir la colonne '{col_ref}'.")

    d = df_maraude.copy()

    d[col_maraude] = pd.to_numeric(d[col_maraude], errors="coerce").astype("Int64")
    ref_ids = pd.to_numeric(df_ref_structure[col_ref], errors="coerce").astype("Int64")

    ref_set = set(ref_ids.dropna().tolist())

    n0 = len(d)
    d = d[d[col_maraude].isin(ref_set)].copy()
    n1 = len(d)

    if verbose:
        print(f"📌 Filtre structures ref: {n1:,}/{n0:,} lignes conservées (supprimées: {n0-n1:,}).")

    return d


# ---------------------------------------------------------------------
# Prep (tables "propres" pour calcul)
# ---------------------------------------------------------------------
def prep_nb_maraudes_sigma(df, filtre_annee_fn=None):
    cols_keep = [
        "maraude_id_fk",
        "maraude_structure_id_fk",
        "maraude_statut",
        "maraude_date_debut",
        "maraude_date_fin",
    ]

    missing = [c for c in cols_keep if c not in df.columns]
    if missing:
        print("Colonnes manquantes:", missing)

    d = df.loc[:, [c for c in cols_keep if c in df.columns]].copy()
    d = d.drop_duplicates()
    d = d.loc[d["maraude_statut"] == "FINISHED"].copy()

    if filtre_annee_fn is not None:
        filtre_annee_fn(d, "maraude_date_debut")

    return d


def prep_nb_personnes_rencontrees_sigma(df, filtre_annee_fn=None):
    cols_keep = [
        "maraude_id_fk",
        "maraude_structure_id_fk",
        "maraude_statut",
        "maraude_date_debut",
        "maraude_date_fin",
        "maraude_rencontre_beneficiaire_id_fk",
        "maraude_rencontre_contact_realise",
        "maraude_rencontre_typologie",
        "maraude_rencontre_nb_hommes",
        "maraude_rencontre_nb_femmes",
        "maraude_rencontre_nb_transgenres",
        "maraude_rencontre_nb_mineurs",
        "maraude_rencontre_nb_inconnus",
    ]

    missing = [c for c in cols_keep if c not in df.columns]
    if missing:
        print("Colonnes manquantes:", missing)

    d = df.loc[:, [c for c in cols_keep if c in df.columns]].copy()
    d = d.drop_duplicates()
    d = d.loc[d["maraude_statut"] == "FINISHED"].copy()
    d = d.loc[d["maraude_rencontre_contact_realise"] == "Oui"].copy()

    if filtre_annee_fn is not None:
        filtre_annee_fn(d, "maraude_date_debut")

    return d


def clean_maraudes(df_maraude):
    """
    Retourne les 2 tables "prep" (maraudes finies / contacts finies).
    """
    df_nb_personnes_rencontrees_sigma = prep_nb_personnes_rencontrees_sigma(df_maraude)
    df_Nb_maraudes_SIGMA_prep = prep_nb_maraudes_sigma(df_maraude)
    return df_nb_personnes_rencontrees_sigma, df_Nb_maraudes_SIGMA_prep


# ---------------------------------------------------------------------
# Calculs (helpers)
# ---------------------------------------------------------------------
def add_nb_personnes(df,
                     out_col="nb personnes",
                     cols=None,
                     col_typologie="maraude_rencontre_typologie"):
    """
    Ajoute une colonne out_col = somme (hommes+femmes+trans+mineurs+inconnus).

    Règle métier ajoutée :
    
    - sinon, on garde la somme.
    - et on conserve ton +1 si typologie == "individu".
    """
    if cols is None:
        cols = [
            "maraude_rencontre_nb_hommes",
            "maraude_rencontre_nb_femmes",
            "maraude_rencontre_nb_transgenres",
            "maraude_rencontre_nb_mineurs",
            "maraude_rencontre_nb_inconnus",
        ]

    d = df.copy()
    missing = [c for c in cols + [col_typologie] if c not in d.columns]
    if missing:
        raise ValueError(f"Colonnes manquantes pour calculer '{out_col}': {missing}")

    d[cols] = d[cols].apply(pd.to_numeric, errors="coerce").fillna(0)
    d[out_col] = d[cols].sum(axis=1)

    # # ✅ Nouvelle règle : si tout est à 0, on met 1
    # d.loc[d[out_col].eq(0), out_col] = 1

    # +1 si typologie == "individu"
    d[out_col] += (d[col_typologie].astype(str).str.strip().str.lower() == "individu").astype(int)

    return d


def Nb_maraudes_SIGMA_DT(df, filtre=None,
                        col_structure="DT_de_rattachement",
                        col_user="Maraude Nb_maraudes_SIGMA",
                        out_col="Maraude Nb_maraudes_SIGMA",
                        fillna_dt=None):
    d = df.query(filtre) if filtre else df

    if fillna_dt is not None:
        d = d.copy()
        d[col_structure] = d[col_structure].fillna(fillna_dt)

    return (
        d.groupby(col_structure, dropna=False)[col_user]
         .sum()
         .rename(out_col)
         .to_frame()
         .reset_index()
    )


def nb_contact_SIGMA_DT(df, filtre=None,
                        col_structure="DT_de_rattachement",
                        col_user="Maraude Nb_contacts",
                        out_col="Maraude Nb_contacts",
                        fillna_dt=None):
    d = df.query(filtre) if filtre else df

    if fillna_dt is not None:
        d = d.copy()
        d[col_structure] = d[col_structure].fillna(fillna_dt)

    return (
        d.groupby(col_structure, dropna=False)[col_user]
         .sum()
         .rename(out_col)
         .to_frame()
         .reset_index()
    )


def nb_personnes_diff_SIGMA_DT(df, filtre=None,
                              col_structure="DT_de_rattachement",
                              col_user="Maraude Nb_personnes_rencontrees",
                              out_col="Maraude Nb_personnes_rencontrees",
                              fillna_dt=None):
    d = df.query(filtre) if filtre else df

    if fillna_dt is not None:
        d = d.copy()
        d[col_structure] = d[col_structure].fillna(fillna_dt)

    return (
        d.groupby(col_structure, dropna=False)[col_user]
         .sum()
         .rename(out_col)
         .to_frame()
         .reset_index()
    )


# ---------------------------------------------------------------------
# Indicateurs (final)
# ---------------------------------------------------------------------
def indicateurs_maraude(df_nb_personnes_rencontrees_sigma,
                        df_Nb_maraudes_SIGMA_prep,
                        df_rattachement_court):
    """
    Calcule :
    - maraudes par structure + DT
    - contacts par structure + DT
    - personnes différentes (max par bénéficiaire) par structure + DT

    Returns
    -------
    df_maraudes_struct
    df_maraudes_dt
    df_contacts_struct
    df_contacts_dt
    df_personnes_diff_base
    df_personnes_diff_struct
    df_personnes_diff_dt
    """

    # --- Normalisation types pour merges ---
    df_ratt = df_rattachement_court.copy()
    if "n_structure" in df_ratt.columns:
        df_ratt["n_structure"] = pd.to_numeric(df_ratt["n_structure"], errors="coerce").astype("Int64")

    # -----------------------------------------------------------------
    # 1) MARAUDES (STRUCT)
    # -----------------------------------------------------------------
    d_m = df_Nb_maraudes_SIGMA_prep.copy()
    d_m = d_m.rename(columns={"maraude_structure_id_fk": "n_structure"})
    d_m["n_structure"] = pd.to_numeric(d_m["n_structure"], errors="coerce").astype("Int64")

    df_maraudes_struct = d_m.groupby("n_structure", as_index=False)["maraude_id_fk"].count()
    df_maraudes_struct.columns = ["n_structure", "Maraude Nb_maraudes_SIGMA"]

    # MARAUDES (DT)
    df_maraudes_struct = pd.merge(df_maraudes_struct, df_ratt, on="n_structure", how="left")
    df_maraudes_dt = Nb_maraudes_SIGMA_DT(df_maraudes_struct)

    # -----------------------------------------------------------------
    # 2) CONTACTS (STRUCT)
    # -----------------------------------------------------------------
    d_c = df_nb_personnes_rencontrees_sigma.copy()
    d_c = d_c.rename(columns={"maraude_structure_id_fk": "n_structure"})
    d_c["n_structure"] = pd.to_numeric(d_c["n_structure"], errors="coerce").astype("Int64")
    d_c = add_nb_personnes(d_c)

    df_contacts_struct = d_c.groupby("n_structure", as_index=False)["nb personnes"].sum()
    df_contacts_struct.columns = ["n_structure", "Maraude Nb_contacts"]

    # CONTACTS (DT)  ✅ on calcule bien sur le df MERGE avec DT
    df_contacts_struct = pd.merge(df_contacts_struct, df_ratt, on="n_structure", how="left")
    df_contacts_dt = nb_contact_SIGMA_DT(df_contacts_struct)

    # -----------------------------------------------------------------
    # 3) PERSONNES DIFFERENTES (BASE + STRUCT + DT)
    # -----------------------------------------------------------------
    # base max par beneficiaire
    df_personnes_diff_base = d_c.loc[
        d_c.groupby("maraude_rencontre_beneficiaire_id_fk")["nb personnes"].idxmax(),
        ["maraude_rencontre_beneficiaire_id_fk", "n_structure", "nb personnes"]
    ].reset_index(drop=True)

    df_personnes_diff_base.columns = [
        "maraude_rencontre_beneficiaire_id_fk",
        "n_structure",
        "Maraude Nb_personnes_rencontrees"
    ]

    # struct (somme)
    df_personnes_diff_struct = (
        df_personnes_diff_base
        .groupby("n_structure", as_index=False)["Maraude Nb_personnes_rencontrees"]
        .sum()
    )

    # DT
    df_personnes_diff_struct = pd.merge(df_personnes_diff_struct, df_ratt, on="n_structure", how="left")
    df_personnes_diff_dt = nb_personnes_diff_SIGMA_DT(df_personnes_diff_struct)

    return (
        df_maraudes_struct,
        df_maraudes_dt,
        df_contacts_struct,
        df_contacts_dt,
        df_personnes_diff_base,
        df_personnes_diff_struct,
        df_personnes_diff_dt,
    )


# ---------------------------------------------------------------------
# Checks / QA
# ---------------------------------------------------------------------
def lignes_vides(df, col_code_structure, label=None, raise_error=False):
    """
    Vérifie si une colonne contient des NaN ou des valeurs vides.
    """
    s = df[col_code_structure]
    lv = df[s.isna() | (s.astype(str).str.strip() == "")]

    col_name = label or col_code_structure
    if not lv.empty:
        msg = f"❌ {len(lv)} valeur(s) manquante(s) ou vide(s) détectée(s) dans '{col_name}'."
        print(msg)
        if raise_error:
            raise ValueError(msg)
        return False, lv
    else:
        print(f"✅ Aucun NaN ou valeur vide détecté dans '{col_name}'.")
        return True, lv


def check_same_col_sum(df_left: pd.DataFrame,
                       df_right: pd.DataFrame,
                       col: str,
                       dropna: bool = True,
                       atol: float = 0.0,
                       rtol: float = 0.0,
                       label: str = "") -> bool:
    """
    Vérifie que la somme de `col` est identique entre 2 DataFrames.
    Affiche ✅ OK / ❌ PAS OK (avec les sommes et la différence si KO).
    """
    if col not in df_left.columns:
        raise KeyError(f"Colonne '{col}' absente de df_left")
    if col not in df_right.columns:
        raise KeyError(f"Colonne '{col}' absente de df_right")

    s1 = pd.to_numeric(df_left[col], errors="coerce")
    s2 = pd.to_numeric(df_right[col], errors="coerce")

    if dropna:
        s1 = s1.fillna(0)
        s2 = s2.fillna(0)

    sum1 = float(s1.sum())
    sum2 = float(s2.sum())
    delta = sum1 - sum2

    ok = abs(delta) <= (atol + rtol * abs(sum2))

    prefix = f"{label} - " if label else ""
    if ok:
        print(f"✅ {prefix}OK : somme(df_left['{col}']) = somme(df_right['{col}'])")
    else:
        print(
            f"❌ {prefix}PAS OK : somme(df_left['{col}']) ≠ somme(df_right['{col}']) "
            f"(df_left={sum1:.0f} ; df_right={sum2:.0f} ; delta={delta:.0f})"
        )

    return ok
