# -*- coding: utf-8 -*-
"""Maraude.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FaJbmfEdUYCexMOVltMrQdpC-5zqV8ul
"""

import traceback
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload
import io
from PyPDF2 import PdfReader, PdfWriter
import json
import gspread
from gspread_dataframe import get_as_dataframe
import pandas as pd
from PyPDF2 import PdfReader, PdfWriter
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
from PyPDF2 import PdfReader, PdfWriter
from matplotlib.figure import Figure
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from reportlab.pdfgen import canvas as rl_canvas
from reportlab.lib.utils import ImageReader
import math
import os
import matplotlib.pyplot as plt
from IPython.display import Image, display
import fitz  # PyMuPDF
from PIL import Image as PILImage
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import matplotlib.ticker as mtick
from matplotlib.patches import Patch
import io
import re
import shutil
import zipfile
from google.colab import drive, files

from google.colab import auth
from google.auth import default
import unicodedata
import re
import torch
from sentence_transformers import SentenceTransformer, util
import sys
sys.path.append(os.path.abspath("/Code-PAT"))
from utils import *


# Import

def import_maraude(client):
  query = """
  SELECT *
  FROM `crf-pat.dataset_PAT_2025.crf_pat_2025_maraude`
  """
  df_maraude = client.query(query).to_dataframe()

  query = """
  SELECT *
  FROM `crf-pat.dataset_PAT_2025.rattachement_court`
  """

  df_rattachement_court = client.query(query).to_dataframe()

  return df_maraude, df_rattachement_court

# Clean

def prep_nb_maraudes_sigma(df, filtre_annee_fn=None):
    cols_keep = ["maraude_id_fk","maraude_structure_id_fk","maraude_statut","maraude_date_debut","maraude_date_fin"]

    missing = [c for c in cols_keep if c not in df.columns]
    if missing:
        print("Colonnes manquantes:", missing)

    d = df.loc[:, [c for c in cols_keep if c in df.columns]].copy()

    d = d.drop_duplicates()

    d = d.loc[d["maraude_statut"] == "FINISHED"].copy()

    if filtre_annee_fn is not None:
        filtre_annee_fn(d, "maraude_date_debut")  # si ta fonction modifie d "in place"
        # ou: d = filtre_annee_fn(d, "maraude_date_debut") si elle retourne un df

    return d


def prep_nb_personnes_rencontrees_sigma(df, filtre_annee_fn=None):
    cols_keep = ["maraude_id_fk","maraude_structure_id_fk","maraude_statut","maraude_date_debut","maraude_date_fin", 'maraude_rencontre_beneficiaire_id_fk',
       'maraude_rencontre_contact_realise', 'maraude_rencontre_typologie',
       'maraude_rencontre_nb_hommes', 'maraude_rencontre_nb_femmes',
       'maraude_rencontre_nb_transgenres', 'maraude_rencontre_nb_mineurs',
       'maraude_rencontre_nb_inconnus']

    missing = [c for c in cols_keep if c not in df.columns]
    if missing:
        print("Colonnes manquantes:", missing)

    d = df.loc[:, [c for c in cols_keep if c in df.columns]].copy()

    d = d.drop_duplicates()

    d = d.loc[d["maraude_statut"] == "FINISHED"].copy()

    d = d.loc[d["maraude_rencontre_contact_realise"] == "Oui"].copy()

    if filtre_annee_fn is not None:
        filtre_annee_fn(d, "maraude_date_debut")  # si ta fonction modifie d "in place"
        # ou: d = filtre_annee_fn(d, "maraude_date_debut") si elle retourne un df

    return d

def clean_maraudes(client):

  df_maraude, df_rattachement_court = import_maraude(client)

  df_nb_personnes_rencontrees_sigma = prep_nb_personnes_rencontrees_sigma(df_maraude)
  df_Nb_maraudes_SIGMA =prep_nb_maraudes_sigma(df_maraude)
  df_Nb_maraudes_SIGMA =prep_nb_maraudes_sigma(df_maraude)

  return df_nb_personnes_rencontrees_sigma, df_Nb_maraudes_SIGMA

#Calcul Structure

def calc_nb_maraudes_sigma(df_prep,
                           col_structure="maraude_structure_id_fk",
                           col_id="maraude_id_fk",
                           out_structure="n_structure",
                           out_count="Maraude Nb_maraudes_SIGMA"):
    df_out = df_prep.groupby(col_structure, as_index=False)[col_id].count()
    df_out.columns = [out_structure, out_count]
    return df_out



def add_nb_personnes(df,
                     out_col="nb personnes",
                     cols=None,
                     col_typologie="maraude_rencontre_typologie"):
    if cols is None:
        cols = [
            "maraude_rencontre_nb_hommes",
            "maraude_rencontre_nb_femmes",
            "maraude_rencontre_nb_transgenres",
            "maraude_rencontre_nb_mineurs",
            "maraude_rencontre_nb_inconnus",
        ]

    d = df.copy()
    missing = [c for c in cols + [col_typologie] if c not in d.columns]
    if missing:
        raise ValueError(f"Colonnes manquantes pour calculer '{out_col}': {missing}")

    d[cols] = d[cols].apply(pd.to_numeric, errors="coerce").fillna(0)
    d[out_col] = d[cols].sum(axis=1)

    # +1 si typologie == "individu"
    d[out_col] += (d[col_typologie].astype(str).str.strip().str.lower() == "individu").astype(int)

    return d

#Calcul DT

def Nb_maraudes_SIGMA_DT(df, filtre=None,
                              col_structure="DT_de_rattachement",
                              col_user="Maraude Nb_maraudes_SIGMA",
                              out_col="Maraude Nb_maraudes_SIGMA"):
    d = df.query(filtre) if filtre else df
    return (d.groupby(col_structure)[col_user]
              .sum()
              .rename(out_col)
              .to_frame() #transforme la serie en dataframe
              .reset_index())

    #Calcul DT

def nb_contact_SIGMA_DT(df, filtre=None,
                              col_structure="DT_de_rattachement",
                              col_user="Maraude Nb_contacts",
                              out_col="Maraude Nb_contacts"):
    d = df.query(filtre) if filtre else df
    return (d.groupby(col_structure)[col_user]
              .sum()
              .rename(out_col)
              .to_frame() #transforme la serie en dataframe
              .reset_index())


def nb_personnes_rencontrees_SIGMA_DT(df, filtre=None,
                              col_structure="DT_de_rattachement",
                              col_user="Maraude Nb_personnes_rencontrees",
                              out_col="Maraude Nb_personnes_rencontrees"):
    d = df.query(filtre) if filtre else df
    return (d.groupby(col_structure)[col_user]
              .sum()
              .rename(out_col)
              .to_frame() #transforme la serie en dataframe
              .reset_index())

def indicateurs_maraude(df_nb_personnes_rencontrees_sigma, df_Nb_maraudes_SIGMA):

