# -*- coding: utf-8 -*-
"""Maraude_manuelle2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14P6mqpRSeAlDkTBVi1l1WXbYKR__wqq5
"""

import traceback
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload
import io
from PyPDF2 import PdfReader, PdfWriter
import json
import gspread
from gspread_dataframe import get_as_dataframe
import pandas as pd
from PyPDF2 import PdfReader, PdfWriter
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
from PyPDF2 import PdfReader, PdfWriter
from matplotlib.figure import Figure
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from reportlab.pdfgen import canvas as rl_canvas
from reportlab.lib.utils import ImageReader
import math
import os
import matplotlib.pyplot as plt
from IPython.display import Image, display
import fitz  # PyMuPDF
from PIL import Image as PILImage
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import matplotlib.ticker as mtick
from matplotlib.patches import Patch
import sys
import io
import re
import shutil
import zipfile
from google.colab import drive, files

from google.colab import auth
from google.auth import default
import unicodedata
import re
import torch
from sentence_transformers import SentenceTransformer, util

sys.path.append(os.path.abspath("/Code-PAT"))
from utils import *

def  Import_Maraude_manuel(client,df_ref_structure):
  # Import
  query = """
    SELECT *
    FROM `crf-pat.dataset_PAT_2025.Maraude_manuelle`
    """
  df_Maraude_donnees_manuelles = client.query(query).to_dataframe()

    #Rapprochement libelles (Move this block up)
  df_Maraude_donnees_manuelles.columns = [unicodedata.normalize('NFKD', col).encode('ascii', 'ignore').decode('utf-8').strip() for col in df_Maraude_donnees_manuelles.columns]

  #Netoyage de la base
  df_Maraude_donnees_manuelles = df_Maraude_donnees_manuelles[~df_Maraude_donnees_manuelles["Departement"].astype(str).str.contains("Total", case=False, na=False)].copy()

  to_drop = {
      "SAMUSO EQUIPE MOBILE DE GUADELOUPE",
      "SEMISS DE LA DROME",
      "SEMISS DE L'AIN",
  }

  df_Maraude_donnees_manuelles = df_Maraude_donnees_manuelles[
      ~df_Maraude_donnees_manuelles["Structure"].astype(str).str.strip().isin(to_drop)
  ].copy()

  df_Maraude_donnees_manuelles["Structure"] = df_Maraude_donnees_manuelles["Structure"].astype(str).map(normalize_structure)
  df_Maraude_donnees_manuelles = rapprochement_libelles(df_ref_structure, df_Maraude_donnees_manuelles, "Structure")

  #Rename des colonnes :
  df_Maraude_donnees_manuelles = df_Maraude_donnees_manuelles.rename(columns={
      "Nb maraude": "Maraude Nb_maraudes_SIGMA",
      "Nb Personnes differentes": "Maraude Nb_personnes_rencontrees",
      "Nb contacts": "Maraude Nb_contacts",
  })

  #rattachement_court
  df_rattachement_court = df_ref_structure[['n_structure', 'DT_de_rattachement']]

  df_Maraude_donnees_manuelles.loc[
      df_Maraude_donnees_manuelles["Structure"].astype(str).str.strip() == "UL DE CONCARNEAU AVEN MOROS",
      "n_structure"
  ] = 2315

  return df_Maraude_donnees_manuelles, df_rattachement_court



def calcul_indic_maraude_manuelles(df_ref_structure, df_Maraude_donnees_manuelles):

  #rattachement successif
  df_ref_structure, c, rattachement_successif, df_Maraude_donnees_manuelles_2 = apply_rattachement_successif(df_ref_structure, df_Maraude_donnees_manuelles, col="n_structure")

  #Rajout structure de ratachement
  df_Maraude_donnees_manuelles_2 = pd.merge(df_Maraude_donnees_manuelles_2, df_rattachement_court, on='n_structure', how="left")

  #Réorganisation de la base

  df_Maraude_donnees_manuelles_DT = df_Maraude_donnees_manuelles_2[['DT_de_rattachement',"Maraude Nb_maraudes_SIGMA", "Maraude Nb_personnes_rencontrees", "Maraude Nb_contacts",]]
  df_Maraude_donnees_manuelles_2 = df_Maraude_donnees_manuelles_2[['n_structure', "Maraude Nb_maraudes_SIGMA", "Maraude Nb_personnes_rencontrees", "Maraude Nb_contacts",]]

  #Calcul maraude manuelle DT
  df_Maraude_donnees_manuelles_DT_2 = (
      df_Maraude_donnees_manuelles_DT
        .groupby("DT_de_rattachement", as_index=False)[
            ["Maraude Nb_maraudes_SIGMA",
            "Maraude Nb_personnes_rencontrees",
            "Maraude Nb_contacts"]
        ]
        .sum()
  )

  #Calcul maraude manuelle structure
  df_Maraude_donnees_manuelles_structure_2 = (
      df_Maraude_donnees_manuelles_2.groupby("n_structure", as_index=False)[[
      "Maraude Nb_maraudes_SIGMA",
      "Maraude Nb_personnes_rencontrees",
      "Maraude Nb_contacts",
  ]].sum())

  return df_Maraude_donnees_manuelles_DT_2, df_Maraude_donnees_manuelles_structure_2

def check_maraude_sums(df, df2):
    cols = [
        "Maraude Nb_maraudes_SIGMA",
        "Maraude Nb_personnes_rencontrees",
        "Maraude Nb_contacts",
    ]
    diff = df[cols].sum(numeric_only=True) - df2[cols].sum(numeric_only=True)

    if (diff == 0).all():
        print("✅ OK — sommes identiques (diff = 0)")
    else:
        diff_ko = diff[diff != 0]
        print("❌ KO — différences sur : " + ", ".join(diff_ko.index.tolist()))
        print(diff_ko)

    return diff