# -*- coding: utf-8 -*-
"""Maraude_manuel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rQxXWVTPvrXNuAFslwvChgZuLR-BN2Pn
"""

def  Import_Maraude_manuel(df_ref_structure):
  # Import
  query = """
    SELECT *
    FROM `crf-pat.dataset_PAT_2025.Maraude_manuelle`
    """
  df_Maraude_donnees_manuelles = client.query(query).to_dataframe()

    #Rapprochement libelles (Move this block up)
  df_Maraude_donnees_manuelles.columns = [unicodedata.normalize('NFKD', col).encode('ascii', 'ignore').decode('utf-8').strip() for col in df_Maraude_donnees_manuelles.columns]

  #Netoyage de la base
  df_Maraude_donnees_manuelles = df_Maraude_donnees_manuelles[~df_Maraude_donnees_manuelles["Departement"].astype(str).str.contains("Total", case=False, na=False)].copy()

  to_drop = {
      "SAMUSO EQUIPE MOBILE DE GUADELOUPE",
      "SEMISS DE LA DROME",
      "SEMISS DE L'AIN",
  }

  df_Maraude_donnees_manuelles = df_Maraude_donnees_manuelles[
      ~df_Maraude_donnees_manuelles["Structure"].astype(str).str.strip().isin(to_drop)
  ].copy()

  df_Maraude_donnees_manuelles["Structure"] = df_Maraude_donnees_manuelles["Structure"].astype(str).map(normalize_structure)
  df_Maraude_donnees_manuelles = rapprochement_libelles(df_ref_structure, df_Maraude_donnees_manuelles, "Structure")

  #Rename des colonnes :
  df_Maraude_donnees_manuelles = df_Maraude_donnees_manuelles.rename(columns={
      "Nb maraude": "Maraude Nb_maraudes_SIGMA_2",
      "Nb Personnes differentes": "Maraude Nb_personnes_rencontrees_2",
      "Nb contacts": "Maraude Nb_contacts_2",
  })

  #rattachement_court
  rattachement_court = df_ref_structure[['n_structure', 'DT_de_rattachement']]

  df_Maraude_donnees_manuelles.loc[
      df_Maraude_donnees_manuelles["Structure"].astype(str).str.strip() == "UL DE CONCARNEAU AVEN MOROS",
      "n_structure"
  ] = 2315

  return df_Maraude_donnees_manuelles, rattachement_court



def calcul_indic_maraude_manuelles(df_ref_structure, df_Maraude_donnees_manuelles):

  #rattachement successif
  df_ref_structure, c, rattachement_successif, df_Maraude_donnees_manuelles_2 = apply_rattachement_successif(df_ref_structure, df_Maraude_donnees_manuelles, col="n_structure")

  #Rajout structure de ratachement
  df_Maraude_donnees_manuelles_2 = pd.merge(df_Maraude_donnees_manuelles_2, rattachement_court, on='n_structure', how="left")

  #Réorganisation de la base

  df_Maraude_donnees_manuelles_DT = df_Maraude_donnees_manuelles_2[['DT_de_rattachement',"Maraude Nb_maraudes_SIGMA_2", "Maraude Nb_personnes_rencontrees_2", "Maraude Nb_contacts_2",]]
  df_Maraude_donnees_manuelles_2 = df_Maraude_donnees_manuelles_2[['n_structure', "Maraude Nb_maraudes_SIGMA_2", "Maraude Nb_personnes_rencontrees_2", "Maraude Nb_contacts_2",]]

  #Calcul maraude manuelle DT
  df_Maraude_donnees_manuelles_DT_2 = (
      df_Maraude_donnees_manuelles_DT
        .groupby("DT_de_rattachement", as_index=False)[
            ["Maraude Nb_maraudes_SIGMA_2",
            "Maraude Nb_personnes_rencontrees_2",
            "Maraude Nb_contacts_2"]
        ]
        .sum()
  )

  #Calcul maraude manuelle structure
  df_Maraude_donnees_manuelles_structure_2 = (
      df_Maraude_donnees_manuelles_2.groupby("n_structure", as_index=False)[[
      "Maraude Nb_maraudes_SIGMA_2",
      "Maraude Nb_personnes_rencontrees_2",
      "Maraude Nb_contacts_2",
  ]].sum())

  return df_Maraude_donnees_manuelles_DT_2, df_Maraude_donnees_manuelles_structure_2

def check_maraude_sums(df, df2):
    cols = [
        "Maraude Nb_maraudes_SIGMA_2",
        "Maraude Nb_personnes_rencontrees_2",
        "Maraude Nb_contacts_2",
    ]
    diff = df[cols].sum(numeric_only=True) - df2[cols].sum(numeric_only=True)

    if (diff == 0).all():
        print("✅ OK — sommes identiques (diff = 0)")
    else:
        diff_ko = diff[diff != 0]
        print("❌ KO — différences sur : " + ", ".join(diff_ko.index.tolist()))
        print(diff_ko)

    return diff