# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ATxYX3x20xYCbT-jl_x2NKE0YIGxbDRa
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile verification.py
# import pandas as pd
# 
# 
# def check_same_col_sum(
#     df_left: pd.DataFrame,
#     df_right: pd.DataFrame,
#     col: str,
#     dropna: bool = True,
#     atol: float = 0.0,
#     rtol: float = 0.0,
#     label: str = "",
# ) -> bool:
#     """
#     Copie du doc : vérifie que la somme de `col` est identique entre 2 DataFrames.
#     Print ✅ / ❌ + sommes + delta.
#     """
#     if col not in df_left.columns:
#         raise KeyError(f"Colonne '{col}' absente de df_left")
#     if col not in df_right.columns:
#         raise KeyError(f"Colonne '{col}' absente de df_right")
# 
#     s1 = pd.to_numeric(df_left[col], errors="coerce")
#     s2 = pd.to_numeric(df_right[col], errors="coerce")
#     if dropna:
#         s1 = s1.fillna(0)
#         s2 = s2.fillna(0)
# 
#     sum1 = float(s1.sum())
#     sum2 = float(s2.sum())
#     delta = sum1 - sum2
#     ok = abs(delta) <= (atol + rtol * abs(sum2))
# 
#     prefix = f"{label} - " if label else ""
#     if ok:
#         print(f"✅ {prefix}OK : somme(df_left['{col}']) = somme(df_right['{col}']) (total={sum1:.0f})")
#     else:
#         print(
#             f"❌ {prefix}PAS OK : somme(df_left['{col}']) ≠ somme(df_right['{col}']) "
#             f"(df_left={sum1:.0f} ; df_right={sum2:.0f} ; delta={delta:.0f} ; total_ref={sum1:.0f})"
#         )
#     return ok
# 
# 
# def run_morocheck(
#     df_Nb_maraudes_SIGMA_struct: pd.DataFrame,
#     df_Nb_maraudes_SIGMA_DT: pd.DataFrame,
#     df_nb_contacts_SIGMA_struct: pd.DataFrame,
#     df_nb_contacts_SIGMA_DT: pd.DataFrame,
#     df_nb_personnes_rencontrees_SIGMA_struct: pd.DataFrame,
#     df_nb_personnes_rencontrees_SIGMA_DT: pd.DataFrame,
#     df_Nb_maraudes_SIGMA: pd.DataFrame,
#     df_maraude_verif: pd.DataFrame,
#     df_personnes_diff_base: pd.DataFrame,
# ) -> None:
#     """
#     Version linéaire basée sur ton doc :
#     #1, #2, #3 : sommes DT vs structure
#     #4 : somme maraudes structure == len(df_Nb_maraudes_SIGMA)
#     #5 : (du doc) vérif contacts (Struct vs df_maraude_verif sur col à comparer)
#     #6 : personnes différentes rencontrées (df_personnes_diff_base vs df_struct)
#     #7 : somme personnes rencontrées (df_struct vs df_maraude_verif['nb personnes'])
#     ⚠️ La vérif diff_nb_personnes (ligne à ligne) a été retirée comme demandé.
#     """
# 
#     print("\n====================")
#     print("MOROCHECK - MARAUDE")
#     print("====================\n")
# 
#     # #1 On vérifie les sommes entre DT et structure (Nb maraudes)
#     ok = check_same_col_sum(
#         df_Nb_maraudes_SIGMA_struct,
#         df_Nb_maraudes_SIGMA_DT,
#         "Maraude Nb_maraudes_SIGMA",
#         label="#1 Nb maraudes (Struct vs DT)"
#     )
#     if not ok:
#         raise ValueError("KO #1 : Nb maraudes Struct vs DT")
# 
#     # #2 On vérifie les sommes entre DT et structure (Nb contacts)
#     ok = check_same_col_sum(
#         df_nb_contacts_SIGMA_struct,
#         df_nb_contacts_SIGMA_DT,
#         "Maraude Nb_contacts",
#         label="#2 Nb contacts (Struct vs DT)"
#     )
#     if not ok:
#         raise ValueError("KO #2 : Nb contacts Struct vs DT")
# 
#     # #3 On vérifie les sommes entre DT et structure (Nb personnes rencontrées)
#     ok = check_same_col_sum(
#         df_nb_personnes_rencontrees_SIGMA_struct,
#         df_nb_personnes_rencontrees_SIGMA_DT,
#         "Maraude Nb_personnes_rencontrees",
#         label="#3 Nb personnes rencontrées (Struct vs DT)"
#     )
#     if not ok:
#         raise ValueError("KO #3 : Nb personnes rencontrées Struct vs DT")
# 
#     # #4 Vérif maraudes : somme maraudes structure == nb maraudes (len df_Nb_maraudes_SIGMA)
#     s_maraudes_struct = df_Nb_maraudes_SIGMA_struct["Maraude Nb_maraudes_SIGMA"].sum()
#     if s_maraudes_struct != len(df_Nb_maraudes_SIGMA):
#         raise ValueError(
#             f"KO #4 : Incohérence maraudes : somme struct={s_maraudes_struct} ≠ len(df_Nb_maraudes_SIGMA)={len(df_Nb_maraudes_SIGMA)}"
#         )
#     else:
#         print("✅ #4 OK : somme maraudes structure = nombre de lignes df_Nb_maraudes_SIGMA")
# 
#     # #5 Vérif de contacts (linéaire, comme dans ton doc)
#     # NB : dans ton doc, tu compares s_struct (contacts struct) à s_base (df_maraude_verif['nb personnes'])
#     # Je garde EXACTEMENT la logique du doc, mais le message précise bien la comparaison.
#     s_struct = df_nb_contacts_SIGMA_struct["Maraude Nb_contacts"].sum()
#     s_base = df_maraude_verif["nb personnes"].sum()
# 
#     if s_struct == s_base:
#         print("✅ #5 OK : somme 'Maraude Nb_contacts' (df_struct) = somme 'nb personnes' (df_maraude_verif)")
#     else:
#         print(f"❌ #5 PROBLÈME : contacts df_struct={s_struct} ≠ nb personnes df_maraude_verif={s_base} (écart={s_base - s_struct})")
#         raise ValueError("KO #5 : incohérence sur la vérif contacts (voir log)")
# 
#     # #6 Personnes différentes rencontrées (df_base vs df_struct)
#     s_base = df_personnes_diff_base["Maraude Nb_personnes_rencontrees"].sum()
#     s_struct = df_nb_personnes_rencontrees_SIGMA_struct["Maraude Nb_personnes_rencontrees"].sum()
# 
#     if s_base != s_struct:
#         diff = s_base - s_struct
#         raise ValueError(
#             f"KO #6 : Incohérence maraudes (personnes différentes rencontrées) : "
#             f"somme df_base={s_base} ≠ somme df_struct={s_struct} (écart={diff})"
#         )
#     else:
#         print(f"✅ #6 OK : personnes différentes rencontrées — somme df_base = {s_base} = somme df_struct = {s_struct}")
# 
#     # #7 Somme personnes rencontrées : df_struct vs df_maraude_verif['nb personnes']
#     s_personnes_rencontre_struct = df_nb_personnes_rencontrees_SIGMA_struct["Maraude Nb_personnes_rencontrees"].sum()
#     t_personnes_rencontre_maraude_verif = df_maraude_verif["nb personnes"].sum()
# 
#     if s_personnes_rencontre_struct != t_personnes_rencontre_maraude_verif:
#         diff = t_personnes_rencontre_maraude_verif - s_personnes_rencontre_struct
#         raise ValueError(
#             f"KO #7 : Incohérence maraudes : somme 'Maraude Nb_personnes_rencontrees' (df structures)={s_personnes_rencontre_struct} "
#             f"≠ somme 'nb personnes' (df_maraude_verif)={t_personnes_rencontre_maraude_verif} "
#             f"(écart={diff})"
#         )
#     else:
#         print("✅ #7 OK : somme df structures = somme df_maraude_verif (nb personnes)")
# 
#     print("\n✅ MOROCHECK terminé : tout est OK.\n")
#