# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Drk5sGfpX9PR0THzbN8RUeBiepNqT96L
"""

import pandas as pd


def check_same_col_sum(
    df_left: pd.DataFrame,
    df_right: pd.DataFrame,
    col: str,
    dropna: bool = True,
    atol: float = 0.0,
    rtol: float = 0.0,
    label: str = "",
) -> bool:
    if col not in df_left.columns:
        raise KeyError(f"Colonne '{col}' absente de df_left")
    if col not in df_right.columns:
        raise KeyError(f"Colonne '{col}' absente de df_right")

    s1 = pd.to_numeric(df_left[col], errors="coerce")
    s2 = pd.to_numeric(df_right[col], errors="coerce")
    if dropna:
        s1 = s1.fillna(0)
        s2 = s2.fillna(0)

    sum1 = float(s1.sum())
    sum2 = float(s2.sum())
    delta = sum1 - sum2
    ok = abs(delta) <= (atol + rtol * abs(sum2))

    prefix = f"{label} - " if label else ""
    if ok:
        print(f"✅ {prefix}OK : somme(df_left['{col}']) = somme(df_right['{col}']) (total={sum1:.0f})")
    else:
        print(
            f"❌ {prefix}PAS OK : somme(df_left['{col}']) ≠ somme(df_right['{col}']) "
            f"(df_left={sum1:.0f} ; df_right={sum2:.0f} ; delta={delta:.0f})"
        )
    return ok


def run_verif_maraude(
    df_Nb_maraudes_SIGMA_struct: pd.DataFrame,
    df_Nb_maraudes_SIGMA_DT: pd.DataFrame,
    df_nb_contacts_SIGMA_struct: pd.DataFrame,
    df_nb_contacts_SIGMA_DT: pd.DataFrame,
    df_nb_personnes_rencontrees_SIGMA_struct: pd.DataFrame,
    df_nb_personnes_rencontrees_SIGMA_DT: pd.DataFrame,
    df_Nb_maraudes_SIGMA: pd.DataFrame,
    df_maraude_verif: pd.DataFrame,
    df_personnes_diff_base: pd.DataFrame,
) -> None:

    print("\n====================")
    print("VERIF MARAUDE")
    print("====================\n")

    # #1 Nb maraudes : Struct vs DT
    ok = check_same_col_sum(
        df_Nb_maraudes_SIGMA_struct,
        df_Nb_maraudes_SIGMA_DT,
        "Maraude Nb_maraudes_SIGMA",
        label="#1 Nb maraudes (Struct vs DT)",
    )
    if not ok:
        raise ValueError("KO #1 : Nb maraudes Struct vs DT")

    # #2 Nb contacts : Struct vs DT
    ok = check_same_col_sum(
        df_nb_contacts_SIGMA_struct,
        df_nb_contacts_SIGMA_DT,
        "Maraude Nb_contacts",
        label="#2 Nb contacts (Struct vs DT)",
    )
    if not ok:
        raise ValueError("KO #2 : Nb contacts Struct vs DT")

    # #3 Nb personnes rencontrées : Struct vs DT
    ok = check_same_col_sum(
        df_nb_personnes_rencontrees_SIGMA_struct,
        df_nb_personnes_rencontrees_SIGMA_DT,
        "Maraude Nb_personnes_rencontrees",
        label="#3 Nb personnes rencontrées (Struct vs DT)",
    )
    if not ok:
        raise ValueError("KO #3 : Nb personnes rencontrées Struct vs DT")

    # #4 Somme maraudes structure == len(df_Nb_maraudes_SIGMA)
    s_maraudes_struct = df_Nb_maraudes_SIGMA_struct["Maraude Nb_maraudes_SIGMA"].sum()
    n_base = len(df_Nb_maraudes_SIGMA)

    if s_maraudes_struct != n_base:
        raise ValueError(
            f"KO #4 : Incohérence maraudes : somme struct={s_maraudes_struct} ≠ len(df_Nb_maraudes_SIGMA)={n_base}"
        )
    else:
        print(f"✅ #4 OK : somme maraudes structure ({s_maraudes_struct}) = len(df_Nb_maraudes_SIGMA) ({n_base})")

    # #5 Personnes différentes rencontrées : df_personnes_diff_base vs df_struct
    s_base = df_personnes_diff_base["Maraude Nb_personnes_rencontrees"].sum()
    s_struct = df_nb_personnes_rencontrees_SIGMA_struct["Maraude Nb_personnes_rencontrees"].sum()

    if s_base != s_struct:
        diff = s_base - s_struct
        raise ValueError(
            f"KO #5 : personnes différentes rencontrées : somme df_base={s_base} ≠ somme df_struct={s_struct} (écart={diff})"
        )
    else:
        print(f"✅ #5 OK : personnes différentes rencontrées — somme df_base = {s_base} = somme df_struct = {s_struct}")

    # #6 Somme personnes rencontrées : df_struct vs df_maraude_verif['nb personnes']
    df_maraude_verif= prep_nb_personnes_rencontrees_sigma(df_maraude, filtre_annee_fn=None)
    df_maraude_verif= add_nb_personnes(df_maraude_verif,
    out_col="nb personnes",
    cols=None,
    col_typologie="maraude_rencontre_typologie")

    s_struct = df_nb_contacts_SIGMA_struct["Maraude Nb_contacts"].sum()
    s_base = df_maraude_verif["nb personnes"].sum()

    if s_struct == s_base:
      print("✅ OK : somme 'Maraude Nb contacts struct' df struct = somme Nb contacts df maraude verif")
    else:
      print(f"❌ PROBLÈME : Maraude Nb_contacts struct={s_struct} ≠ somme Nb_contacts df_maraude_verif={s_base} (écart={s_base - s_struct})")
